---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
spec:
  minReadySeconds: 10
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: mysql
          image: sunilkumardasu/mysql
          command: ["/bin/sh", "-ce", "tail -f /dev/null"]
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysqlvolume
          env:
            - name: MYSQL_DATABASE
              value: 'test'
            - name: MYSQL_USER
              value: 'root'
            - name: MYSQL_PASSWORD
              value: 'Newuser@123'
            - name: MYSQL_ROOT_PASSWORD
              value: 'Newuser@123'
      volumes:
      - name: mysqlvolume
        persistentVolumeClaim:
          claimName: pvc-demo

---
apiVersion: v1
kind: Service
metadata:
  name: mysqlsvc
spec:
  selector:
    app: db
  type: ClusterIP
  ports:
    - name: mysql
      targetPort: 3306
      port: 3306